// Vendor
import '@angular/common';
import '@angular/compiler';
import '@angular/core';
import '@angular/forms';
import '@angular/http';
import '@angular/platform-browser';
import '@angular/platform-browser-dynamic';
import 'moment';
import 'ngx-bootstrap';
import 'reflect-metadata';
import 'rxjs';
